x-environment-defaults: &default-env
  DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
  MONGO_URL: "mongodb://mongo:27017/easyfoodapp"
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: "/app"

services:
  frontend:
    container_name: easyfood-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_VERSION: "20"
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "3040"]
    ports:
      - "3040:3040"
    environment:
      CI: "true"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - easyfood_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "main.py"]
    container_name: easyfood-backend
    ports:
      - "8040:8040"
    environment:
      <<: *default-env
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - easyfood_net

  celery:
    container_name: easyfood-celery
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["celery", "-A", "config.celeryConfig.celery_app", "worker", "-l", "info", "--pool=solo"]
    environment:
      <<: *default-env
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
    networks:
      - easyfood_net

  db:
    image: postgres:16
    container_name: easyfood-psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 20
    networks:
      - easyfood_net

  mongo:
    image: mongo:7
    container_name: easyfood-mongo
    environment:
      MONGO_INITDB_DATABASE: easyfoodapp
    volumes:
      - mongodata:/data/db
    ports:
      - "27018:27017"
    networks:
      - easyfood_net

  redis:
    image: redis:7
    container_name: easyfood-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    networks:
      - easyfood_net

networks:
  easyfood_net:

volumes:
  pgdata:
  mongodata:
